=== Levitanishe/agilians/Leave_Request_API-v0.2/holidayAgreement.list.schema.json
{  
  "$schema":"http://json-schema.org/draft-04/schema#",
  "type":"array",
  "items":{  
    "type":"object",
    "id":"HolidayAgreement",
    "properties":{  
      "employeeId":{  
        "type":"string"
      },
      "id":{  
        "type":"string"
      },
      "createdOn":{  
        "type":"array",
        "items":{  
          "type":"integer"
        }
      },
      "modifiedOn":{  
        "type":"array",
        "items":{  
          "type":"integer"
        }
      },
      "dayOfAbsenceLimits":{  
        "type":"array",
        "items":{  
          "type":"object",
          "id":"DayOfAbsenceLimit",
          "properties":{  
            "typeOfAbsence":{  
              "type":"string"
            },
            "maximumCount":{  
              "type":"integer"
            }
          }
        },
        "required":[  
          "typeOfAbsence",
          "maximumCount"
        ]
      },
      "createdBy":{  
        "type":"string"
      },
      "modifiedBy":{  
        "type":"string"
      },
      "validFrom":{  
        "type":"array",
        "items":{  
          "type":"integer"
        }
      },
      "validUntil":{  
        "type":"array",
        "items":{  
          "type":"integer"
        }
      },
      "agreedOn":{  
        "type":"array",
        "items":{  
          "type":"integer"
        }
      },
      "agreedBy":{  
        "type":"string"
      }
    },
    "required":[  
      "agreedBy",
      "validUntil",
      "employeeId",
      "validFrom",
      "agreedOn"
    ]
  }
}

=== Levitanishe/agilians/Leave_Request_API-v0.2/holidayAgreement.sample.json
{
  "createdOn" : [ 2015, 11, 16 ],
  "createdBy" : "hello.world",
  "modifiedOn" : [ 2015, 11, 16 ],
  "modifiedBy" : "hello.world.mod",
  "id" : "id123",
  "agreedOn" : [ 2015, 11, 16 ],
  "agreedBy" : "agile.agilians",
  "employeeId" : "emp123",
  "validFrom" : [ 2015, 11, 16 ],
  "validUntil" : [ 2015, 11, 16 ],
  "dayOfAbsenceLimits" : [ {
    "maximumCount" : 10,
    "typeOfAbsence" : "PUBLIC_HOLIDAY"
  } ]
}
