=== Levitanishe/agilians/Leave_Request_API-v0.2/leaveRequest.schema.json
{
   "$schema":"http://json-schema.org/draft-04/schema#",
   "type":"object",
   "id":"LeaveRequest",
   "properties":{  
      "id":{  
         "type":"string"
      },
      "createdOn":{  
         "type":"array",
         "items":{  
            "type":"integer"
         }
      },
      "modifiedOn":{  
         "type":"array",
         "items":{  
            "type":"integer"
         }
      },
      "approvals":{  
         "type":"array",
         "items":{  
            "type":"object",
            "id":"Approval",
            "properties":{  
               "remarks":{  
                  "type":"string"
               },
               "approvedBy":{  
                  "type":"string"
               },
               "outcome":{  
                  "type":"string"
               },
               "approvedOn":{  
                  "type":"array",
                  "items":{  
                     "type":"integer"
                  }
               }
            }
         },
         "required":[  
            "approvedOn",
            "approvedBy",
            "outcome"
         ]
      },
      "submittedOn":{  
         "type":"array",
         "items":{  
            "type":"integer"
         }
      },
      "createdBy":{  
         "type":"string"
      },
      "status":{  
         "type":"string"
      },
      "modifiedBy":{  
         "type":"string"
      },
      "attachments":{  
         "type":"array",
         "items":{  
            "type":"string"
         }
      },
      "notes":{  
         "type":"string"
      },
      "submittedBy":{  
         "type":"string"
      },
      "dayOfAbsences":{  
         "type":"array",
         "items":{  
            "type":"object",
            "id":"DayOfAbsence",
            "properties":{  
               "type":{  
                  "type":"string"
               },
               "date":{  
                  "type":"array",
                  "items":{  
                     "type":"integer"
                  }
               }
            }
         },
         "required":[  
            "date",
            "type"
         ]
      }
   },
   "required":[  
      "status",
      "submittedOn",
      "submittedBy"
   ]
}

=== Levitanishe/agilians/Leave_Request_API-v0.2/leaveRequest.sample.json
{
  "createdOn" : [ 2015, 11, 16 ],
  "createdBy" : "hello.world",
  "modifiedOn" : [ 2015, 11, 16 ],
  "modifiedBy" : "hello.world.mod",
  "id" : "id123",
  "submittedOn" : [ 2015, 11, 16 ],
  "submittedBy" : "agile.agilians",
  "attachments" : [ "attach1", "attach2" ],
  "notes" : "notes 123",
  "status" : "NEW",
  "dayOfAbsences" : [ {
    "date" : [ 2015, 11, 16 ],
    "type" : "PUBLIC_HOLIDAY"
  }, {
    "date" : [ 2015, 11, 16 ],
    "type" : "PRIVATE_HOLIDAY"
  } ],
  "approvals" : [ {
    "approvedBy" : "agile.agilians1",
    "approvedOn" : [ 2015, 11, 16 ],
    "remarks" : "remarks 123",
    "outcome" : "SENT_FOR_REVIEW"
  }, {
    "approvedBy" : "agile.agilians2",
    "approvedOn" : [ 2015, 11, 16 ],
    "remarks" : "remarks 234",
    "outcome" : "APPROVED"
  } ]
}
